# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Compile
  displayName: 'Preparation [GIT]'

- script: echo Build
  displayName: 'Build [MAVEN]'

- script: echo Unit Testing
  displayName: 'Code Analysis [SONAR]'

- script: echo Environment
  displayName: 'Deployment [DOCKER]'

- script: echo Application Deployment
  displayName: 'Staging'

- script: echo Test
  displayName: 'Prepare Testing'

- script: echo Start Tosca API Tests
  displayName: 'API Testing'

- script: echo Start Selenium Integration Tests
  displayName: 'Integration Testing'

- script: echo Start Tosca Funtional UI Tests
  displayName: 'Functional Regression Testing'

- script: |
    echo Start NeoLoad infrastructure
    echo Execute Performance Tests
  displayName: 'Performance Testing'