name: GitHub Action For Running Tosca
run-name: ${{ github.actor }} is Running Tosca Tests via the AOS API 🚀
on: [push,workflow_dispatch]
jobs:
  Execute-Tosca-Tests:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Tosca Tests on Demo VM
        run: |  
          .\tosca_execution_client.ps1 -toscaServerUrl "http://localhost:80" -projectName "common_repository" -eventsConfigFilePath "testEvents.json" -clientId "pLCD-s_I7UWieIPIHcAHVA" -clientSecret "nvummXXOH0StbMwdHJBAyA0_Bfyb6z7Eqi6mO9hJpfwg" -creator "Github Actions -ToscaExecutionClient" -debug "true" -executionEnvironment "Dex" -pollingInterval 10
      - name: Process JUnit Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: |
            results/*.results.xml
